# Generated by Django 5.1.3 on 2024-12-19 07:51

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_lastname', models.CharField(max_length=50)), # Laststname of the employee
                ('employee_firstname', models.CharField(max_length=50)), # Firstname of the employee
                ('employee_email', models.EmailField(max_length=200)), # Email and Login ID of the employee,
                ('password', models.CharField(max_length=200)), # Password of the employee (hashed)
                ('last_login', models.DateTimeField(auto_now=True)), # Last time the employee logged in
            ],
        ),
    ]
