# Generated by Django 5.1.3 on 2024-12-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField( # Add the field role to separate classic users from admins
            model_name='employee',
            name='role',
            field=models.CharField(default='employee', max_length=100),
        ),
        migrations.AlterField( # Employee Email field must be Unique
            model_name='employee',
            name='employee_email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
