# Generated by Django 5.1.3 on 2024-12-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_role_alter_employee_employee_email'),
    ]

    operations = [
        migrations.AlterField( # This was due to a test after a problem during development
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
