# Generated by Django 5.1.3 on 2025-01-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField( # This was due to a test after a problem during development
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
