# Generated by Django 5.1.3 on 2025-01-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_connexion',
            field=models.BooleanField(default=True),
        ),
    ]
