# Generated by Django 5.1.3 on 2024-11-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel( # Intisialisation of the Table of applications for job offers (Version 1)
            name='Applicaion', #Mistype, has been corrected to Application
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=11)), #Unique (-> Modif N°3) Application number (Format : YYYYMMDDNNN)
                ('candidate_firstname', models.CharField(max_length=50)), #Candidate's firstname
                ('candidate_lastname', models.CharField(max_length=50)), #Candidate's lastname
                ('candidate_mail', models.CharField(max_length=100)), #Candidate's mail
                ('candidate_phone', models.CharField(max_length=10)), #Candidate's phone number (FR format expected)
                ('candidate_password', models.CharField(max_length=200)), #Candidate's password (hashed)
                ('post_id', models.IntegerField()), #Id of the job offer
                ('creation_date', models.DateTimeField(auto_now_add=True)), #Creation date of the application
            ],
        ),
    ]
