# Generated by Django 5.1.3 on 2024-11-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_application_delete_applicaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_number', #Set application number to unique
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
