# Generated by Django 5.1.3 on 2024-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_application_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_login', # add last_login field for authentication
            field=models.DateTimeField(auto_now=True),
        ),
    ]
