# Generated by Django 5.1.3 on 2024-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_application_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status', # adds a status field to determine the advancement of the application (In examination, Refused, Accepted)
            field=models.CharField(default="En Cours D'Examen", max_length=30),
        ),
    ]
