# Generated by Django 5.1.3 on 2024-12-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate_phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True), # Correction : phone number is optional
        ),
    ]
