# Generated by Django 5.1.3 on 2024-12-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_alter_application_candidate_phone'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application', # Create a relation between Application (job_publication) and the Publication model
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='visitor.publication'),
        ),
    ]
