# Generated by Django 5.1.3 on 2025-01-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_rename_post_id_application_job_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
