# Generated by Django 5.1.3 on 2025-01-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_application_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
