# Generated by Django 5.1.3 on 2025-01-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_alter_application_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate_phone',
            field=models.CharField(default='Inconnu', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
