# Generated by Django 5.1.3 on 2025-01-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='candidate', max_length=10),
        ),
    ]
