# Generated by Django 5.1.3 on 2025-01-30 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_remove_message_receiver_id_remove_message_sender_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(default='Entretien', max_length=100)),
                ('date', models.DateTimeField(default='2000-01-01')),
                ('interview_category', models.CharField(default='Autre', max_length=100)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.thread')),
            ],
        ),
    ]
