# Generated by Django 5.1.3 on 2024-11-26 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel( #Initislisation of the Job Offer Publication Table
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)), #Title of the publication / job offer
                ('description', models.TextField(max_length=500)), #Description of the publication / job offer
                ('creation_date', models.DateTimeField(auto_now_add=True)), #Creation date of the publication / job offer
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), #ID of the employee that created the publication
            ],
        ),
    ]
