# Generated by Django 5.1.3 on 2025-01-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_id'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='employee.employee'),
        ),
    ]
