# Generated by Django 5.1.3 on 2025-01-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_first_connexion'),
        ('visitor', '0002_alter_publication_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(1), to='employee.employee'),
        ),
    ]
