# Generated by Django 5.1.3 on 2025-02-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_alter_publication_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
